# --- !Ups

insert into inventory_category(name) value ('General');

# Data for Sobeys Flyer. Inserting into the item DB

insert into item(name, description, category_id, creation_date, modify_date) values ('Schneider\'s Juicy Jumbos','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Schneider\'s Juicy Jumbos','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Maple Leaf Lunch Mates, Stackers Or Kits','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Schneiders Grill\'ems','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Asparagus','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Blueberries','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Pork Loin Sirloin Or Pork Loin Rib Half','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Sterling Silver Boneless Blade Roast Or Steaks','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Fresh Cooked Canner Lobsters','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Nestlé Natural Spring Water','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Minute Maid, Five Alive, Or Nestea Tetra Drinks','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Chapman\'s Original Ice Cream','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Lean Cuisine, Stouffer\'s Entrees, Bistro Crustini','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Large Eggs','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Natrel Premium Flavoured Milk','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Natur A Soy Milk','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Sour Cream','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('French\'s Prepared Mustard','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Del Monte Fruit','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Heinz Beans','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Sugardale Bacon','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Sun•Maid Raisin Bread','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Schneider\'s Fat Free Or Maple Leaf Natural Selections Turkey Breast Roast','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Ontario Ravioli Frozen Pastas','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Liberté Greek Yogourt','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Classico Pasta Sauce','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Coco Libre Coconut Water','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Danone Oikos Greek Yogourt','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Sensations By Compliments Ice Cream','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Sweetener','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Down Under Hair Care','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Zaz Liquid Flavoured Water Enhancer','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Salad Dressing','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Post Honey Bunches Of Oats','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Clover Leaf Albacore Tuna','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Mc Cain Fries','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Lemonade Or Iced Tea','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Becel Margarine','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Jams Or Spreads','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Sensations By Compliments Kettle Corn','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Di Manno Bakery Bread Sticks','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Dove Or Degree Deodorant','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Smuckers Ice Cream Topping','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Diana Sauce','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Flour','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Ivory Bodywash Or Bar Soap','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Dryer Sheets','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Danino Go','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Red Or Green Leaf Lettuce','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Organic Red Tomatoes On The Vine','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Red Prince Apples','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Rainier Cherries','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Organic Sweet Coloured Peppers','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Yellow Or White Flesh Tree Rippened Peaches Or Nectarines','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Hot House Tomatoes','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Seedless Cucumbers','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Pom Pistachios Or Almonds','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Large Seedless Watermelon','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Seedless Mini Cucumbers','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Rainbow Peppers','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Organic Raspberries','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Organic Cherries','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Yellow Tomatoes','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Earthbound Farms Organic Dried Fruit','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Organic Baby Peeled Carrots','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Green Tomatoes','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Organic Or Earthbound Organic Salads','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Organic Bosc Pears','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Patio Planters For Your Balcony','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Loose Bulk','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Premium Perennials','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('The Canadian Chuck Poutine Burger','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Sterling Silver T Bone Grilling Steak','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Pork Back Ribs','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Sterling Silver Inside Round Marinating Steak','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Veal Leg Scallopini','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Prime Thin Slice Chicken Breast','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Sensations By Compliments Split Turkey Breast','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('In Store Made Chicken Or Beef Kabobs','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Balance Lean Ground Pork','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Aspen Ridge Striploin Steaks','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Du Breton Pork Tenderloin','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('High Liner Market Cuts, Salmon, Cod Or Haddock Loins','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Fresh Atlantic Salmon Fillets','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Sensations By Compliments Jumbo Black Tiger Shrimp','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Fresh Tilapia Fillets','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Sea Delight Wild Tuna Or Swordfish Steaks','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Prime Fully Cooked Turkey Or Chicken Strips','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Sensations By Compliments Pork Back Ribs','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Pinty\'s Pub & Grill Chunks, Fillets Or Wings','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Schneider\'s Country Naturals Beef, Turkey Or Chicken Burgers','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Pork Dinner Sausages','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Gourmet Smoked Chicken Sausages','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Souvlaki Pork Kabobs','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Sweet Chili Lime Or Sweet Bbqbutterflied Pork Tenderloin','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Frozen Lamb Spiedini','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('100% Butter Croissants, Danish Or Twists','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Triple Layer 1/4 Slab Celebration Cakes','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Real Cream Layered Cakes','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Gourmet Buns Or Cheese Sticks','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Homestyle Rye Breads','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Cookies Or Muffins','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Villaggio Bread','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Stonemill Breads','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Dimpflmeier Sschweden Brot Light Bread','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Danish Rings','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Hotdog And Hamburger Buns','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('In Store Granola','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Babybel Cheese','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Buy Deli Prepared Atlantic Canadian Lobster Roll Sandwich','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Tre Stelle Mozzarella Cheese','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Mastro Genoa Salami','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Organic Bananas','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Made Fresh Daily Fruit Bowls','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Made Fresh Daily Regular Or Greek Yogurt Bowls','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Organic Mangoes','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Sensations Hummus','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Al Watan Pitas','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Gallo Olive Oil','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Nestlé Natural Spring Water','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Large Eggs','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Quaker Oats','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Dempster\'s Whole Grains Bread','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Sealtest Milk 2%, 1% Or Skim','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Condensed Milk','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Santosh Roti','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Cilantro, Bunch Or Curley Parsley','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Kitchens Of India Sauces Or Curry','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Bard Valley Medjool Dates','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Apricots Or Figs','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Long Squash','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Patak\'s Cooking Sauce','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Garlic','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Unico Vegetable Oil','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Adora Basmati Rice','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Unico Beans','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Krinos Twisters','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Coca Cola Or Pepsi Soft Drinks','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Lay\'s Family Size Chips','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Monster Energy Product','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Powerade','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Pure Leaf Iced Tea','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Dentyne Gum Bottles','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Sun Rype 100% Juices Or Blends','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('San Pellegrino Sparkling Fruit Beverages','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Lipton Specialty Tea','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Post Shreddies Morning Break Snack Mix','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Sensations By Compliments Almond Butter','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Camerons Single Serve Coffee','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Nesquick Syrup','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Cookie It Up','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Kellogg\'s Kashi Crackers','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Grissol Crispy Baguettes Or Thins','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Dr. Oetker Pie Filling','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Robin Hood Quick Bread Mixes','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Carnations Evaporated Milk','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Knorr Dry Soup Or Sauce Mix','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Corn Or Canola Oil','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Salsa','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Bick\'s Sandwich Savers Or Crunch‘Ems','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Heinz Ketchup','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Campbell\'s Everyday Gourmet','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Uncle Ben\'s Side Dishes Express','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Italpasta','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Nabob Ground Or Whole Bean Coffee','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Betty Crocker Cake Mixes','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Betty Crocker Cupcake Or Dessert Bars','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Cheese Bars','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Tropicana Chilled Beverages','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Black Diamond Slices','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Iögo Yogurt','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Jell O Refrigerated Pudding Or Gel','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Balance Liquid Egg Whites','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Néstle Coffee Mate Or International Delight Coffee Whitener','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Sensations By Compliments Pizza','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Mc Cain Pizza Pockets','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Mc Cain Regular Fries','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Mc Cain Desserts Deep N’ Delicious','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Welch\'s Frozen Fruit','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Mc Cain Potato Patties','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Kellogg\'s Eggo Waffles','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Blue Water Valuepack Seafood','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Signal Frozen Punches','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Just Chillin’ Frozen Edamame','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Manitoba Harvest Hemp Hearts','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Jordan\'s Cereal','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Natrel Organic Milk','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Skinny Pop Kettle Corn','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Terra Chips','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Power Bar Energy Bar','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Liberté Organic Yogourt','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Lysol Disinfecting Wipes','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Liquid Plumr Hair Clog Eliminator','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Green Works All Purpose Cleaner','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Febreze Air Effects','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Natures Clean Laundry Detergent','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Gillette Or Venus Disposables Razors','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Vaseline Lotion Or St. Ives Face Care','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Organix Hair Care','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Gillette Or Venus Shave Prep','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Foaming Hand Soap','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Mouthwash','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Dog Food','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Misfits Treats For Dogs','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Cat Food','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Cesar Softies Treats For Small Dogs','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Temptationss Treats For Cats','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Whiskas Dry Food For Cats','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Cesar Wet Food For Small Dogs','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('In Store Made Meat Kabobs','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Baking Potatoes','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Sensations By Compliments No Limits Bbq Sauce','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Fresh Cooked Canner Lobsters','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Du Breton Pork Tenderloin','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Large Lemons','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Garlic','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Veal Leg Scallopini','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('Compliments Baby Spinach','',1,NOW(),NOW());
insert into item(name, description, category_id, creation_date, modify_date) values ('San Daniele Sliced Prosciutto','',1,NOW(),NOW());


# --- !Downs